// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDKhgkKPS7MTuJceUf3HMJjKHD1hyUp1I',
    appId: '1:344695926542:web:3eb0eb3d4f98c15807315f',
    messagingSenderId: '344695926542',
    projectId: 'toni-case-study',
    authDomain: 'toni-case-study.firebaseapp.com',
    storageBucket: 'toni-case-study.appspot.com',
    measurementId: 'G-HB4L5JS9MG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVq0fuETWpwtzIhf-YsjOcWx5AEYgHSuc',
    appId: '1:344695926542:android:cb7d3c727e6c6f4207315f',
    messagingSenderId: '344695926542',
    projectId: 'toni-case-study',
    storageBucket: 'toni-case-study.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGRrXwwDz6tIRy6JoSvXKHgArXPcVNaOE',
    appId: '1:344695926542:ios:476f61449075341e07315f',
    messagingSenderId: '344695926542',
    projectId: 'toni-case-study',
    storageBucket: 'toni-case-study.appspot.com',
    iosBundleId: 'com.example.toniCaseStudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGRrXwwDz6tIRy6JoSvXKHgArXPcVNaOE',
    appId: '1:344695926542:ios:70ea38dab876056a07315f',
    messagingSenderId: '344695926542',
    projectId: 'toni-case-study',
    storageBucket: 'toni-case-study.appspot.com',
    iosBundleId: 'com.example.toniCaseStudy.RunnerTests',
  );
}
